trigger:
- master

resources:
  repositories:
    - repository: azure-sdk-tools
      type: github
      name: Azure/azure-sdk-tools
      endpoint: azure
      ref: refs/tags/azure-sdk-tools_20210707.1

pool:
  vmImage: 'ubuntu-latest'

variables:
  BUNDLE_PATH: $(Pipeline.Workspace)/.bundle

steps:
- checkout: self
- checkout: azure-sdk-tools

# - pwsh: |
#     Write-Host "RepoName = https://github.com/Azure/azure-sdk"
#     Write-Host "RepoName = https://github.com/azure/azure-sdk"
#     Write-Host "##[group]Beginning of a group"
#     Write-Host "##[warning]Warning message"
#     Write-Host "##[error]Error message"
#     Write-Host "##[section]Start of a section"
#     Write-Host "##[debug]Debug text"
#     Write-Host "##[command]Command-line being run"
#     Write-Host "##[endgroup]"

#     Write-Host "##[error]This should be an error"
#     Write-Host "##vso[task.logissue type=error]Force a log issue as error"
#   displayName: Testing some stuff
#   continueOnError: true

- task: Cache@2
  inputs:
    key: 'gems | "$(Agent.OS)" | $(Build.SourcesDirectory)/azure-sdk/Gemfile | $(Build.SourcesDirectory)/azure-sdk/Gemfile.lock'
    path: $(BUNDLE_PATH)
  displayName: Cache gems

- task: UseRubyVersion@0
  inputs:
    versionSpec: '2.7.x'
  displayName: Initialize Ruby

- script: |
    gem install bundler
  displayName: Install bundler
  workingDirectory: azure-sdk

- script: |
    bundle install
  displayName: Install project dependencies
  workingDirectory: azure-sdk

- script: |
    bundle exec jekyll build --future
  displayName: Build Site
  workingDirectory: azure-sdk

- task: PowerShell@2
  displayName: Verify CSV data contents
  inputs:
    pwsh: true
    workingDirectory: azure-sdk
    filePath: azure-sdk/eng/scripts/Update-Release-Versions.ps1
    arguments: "check"

- task: PowerShell@2
  displayName: Verify site links
  inputs:
    pwsh: true
    workingDirectory: azure-sdk
    filePath: azure-sdk/eng/common/scripts/Verify-Links.ps1
    arguments: >
      -urls ./README.md
      -ignoreLinksFile ./eng/ignore-links.txt
      -inputCacheFile "https://azuresdkartifacts.blob.core.windows.net/verify-links-cache/verify-links-cache.txt"
      -devOpsLogging:$true
      -baseUrl "file://$PWD/_site/azure-sdk"
