trigger:
- master

resources:
  repositories:
    - repository: azure-sdk-tools
      type: github
      name: Azure/azure-sdk-tools
      endpoint: azure
      ref: refs/tags/azure-sdk-tools_20210114.1

pool:
  vmImage: 'ubuntu-latest'

steps:
- checkout: self
- checkout: azure-sdk-tools

- task: UseRubyVersion@0
  inputs:
    versionSpec: '2.7.2'
  displayName: Initialize Ruby

- script: |
    gem install jekyll bundler
  displayName: Install jekyll and bundler
  workingDirectory: azure-sdk

- script: |
    bundle install
  displayName: Install project dependencies
  workingDirectory: azure-sdk

- script: |
    bundle exec jekyll build --future
  displayName: Build Site
  workingDirectory: azure-sdk

- task: PowerShell@2
  displayName: Verify CSV data contents
  inputs:
    pwsh: true
    workingDirectory: azure-sdk
    filePath: azure-sdk/eng/scripts/Update-Release-Versions.ps1 
    arguments: "check"

- task: PowerShell@2
  displayName: Verify site links
  inputs:
    pwsh: true
    workingDirectory: azure-sdk
    filePath: azure-sdk-tools/eng/common/scripts/Verify-Links.ps1 
    arguments: >
      -urls ./_site/index.html
      -ignoreLinksFile ./eng/ignore-links.txt
      -devOpsLogging:$true
