
jobs:
- job:
  displayName: Job1
  pool:
    name: azsdk-pool-mms-ubuntu-2204-general
    vmImage: ubuntu-22.04

  steps:
  - pwsh: |
      Write-Host "Job1"
    displayName: Validate Impacted Specs
    condition: succeededOrFailed()

- job:
  displayName: Job2
  pool:
    name: azsdk-pool-mms-ubuntu-2204-general
    vmImage: ubuntu-22.04

  steps:
  - pwsh: |
      Write-Host "Job2"
    displayName: Run Prettier
    condition: succeededOrFailed()

  - pwsh: |
      $sha = git show-ref -s HEAD
      Write-Host $sha
      gh api repos/Azure/azure-rest-api-specs/commits/$sha/check-runs --jq .check_runs.[].name
    displayName: List checks
    env:
      GH_TOKEN: $(System.AccessToken)
