
jobs:
- job:
  displayName: Job1
  pool:
    name: azsdk-pool-mms-ubuntu-2204-general
    vmImage: ubuntu-22.04

  steps:
  - pwsh: |
      Write-Host "Job1"
    displayName: Validate Impacted Specs
    condition: succeededOrFailed()

- job:
  displayName: Job2
  pool:
    name: azsdk-pool-mms-ubuntu-2204-general
    vmImage: ubuntu-22.04

  steps:
  - pwsh: |
      Write-Host "Job2"
    displayName: Run Prettier
    condition: succeededOrFailed()