trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- pwsh: |
    dir env:

- task: GitHubComment@0
  inputs:
    gitHubConnection: 'Azure'
    comment: |
      Test PR commenting

- pwsh: |
    dir env:
    Write-Host "--SYSTEM_ACCESSTOKEN = [$($env:SYSTEM_ACCESSTOKEN)]"
    Write-Host "--System.AccessToken = [$(System.AccessToken)])"
    Write-Host "--ENDPOINT_AUTH_AZURE = [$($env:ENDPOINT_AUTH_AZURE)]"
    Write-Host "--System.EndPoint.Auth.Azure = [$(System.EndPoint.Auth.Azure)]"
    Write-Host "--System.EndPoint_Auth_Azure = [$(System.EndPoint_Auth_Azure)]"

- task: UseRubyVersion@0
  inputs:
    versionSpec: '>= 2.4'
  displayName: Initialize Ruby

- script: |
    gem install jekyll bundler
  displayName: Install jekyll and bundler

- script: |
    bundle install
  displayName: Install project dependencies

- script: |
    bundle exec jekyll build
  displayName: Build Site

- script: |
    bundle exec jekyll serve --detach
  displayName: Launch local site

- script: >
    docker run --net=host --rm weshaggard/linkchecker "http://localhost:4000/index.html"
    --anchors
    --check-extern
    --no-robots
    --no-status
    --no-warnings
    --no-follow-url "https://azure.github.io/azure-sdk-for-*"
    --no-follow-url "https://azure.github.io/azure-cosmos-*"
    --ignore-url "https://github.com/Azure/azure-sdk-pr"
  displayName: 'azure-sdk link check'
  continueOnError: true

- script: |
    pkill -f jekyll
  displayName: Shutdown local site
  condition: always()