trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: UseRubyVersion@0
  inputs:
    versionSpec: '>= 2.4'
  displayName: Initialize Ruby

- script: |
    gem install jekyll bundler
  displayName: Install jekyll and bundler

- script: |
    bundle install
  displayName: Install project dependencies

- script: |
    bundle exec jekyll build
  displayName: Build Site

- script: |
    bundle exec jekyll serve --detach
  displayName: Launch local site

- script: >
    docker run --net=host --rm linkchecker/linkchecker
    "http://localhost:4000/index.html"
    --anchors
    --no-robots --no-status
    --no-follow-url "https://azure.github.io/azure-sdk-for-*"
    --no-follow-url "http://localhost:4000/releases/latest/all/*"
    --ignore-url "https://github.com/Azure/azure-sdk-pr"
  displayName: Verify Links

- script: |
    pkill -f jekyll
  displayName: Shutdown local site
  condition: always()