
jobs:
- job:
  displayName: Job1
  pool:
    name: azsdk-pool-mms-ubuntu-2204-general
    vmImage: ubuntu-22.04

  steps:
  - checkout: self
    persistCredentials: true

  - pwsh: |
      git config -l
    displayName: check git config
    condition: succeededOrFailed()


- job:
  displayName: Job2
  pool:
    name: azsdk-pool-mms-ubuntu-2204-general
    vmImage: ubuntu-22.04

  steps:
  - checkout: self
    persistCredentials: true

  - pwsh: |
      git config -l
    displayName: check git config
    condition: succeededOrFailed()

  - pwsh: |
      $sha = git show-ref -s HEAD
      Write-Host $sha
      gh api repos/Azure/azure-rest-api-specs/commits/$sha/check-runs --jq .check_runs.[].name
    displayName: List checks
    env:
      GH_TOKEN: $(System.AccessToken)
