trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: UseRubyVersion@0
  inputs:
    versionSpec: '>= 2.4'
  displayName: Initialize Ruby

- script: |
    gem install jekyll bundler
  displayName: Install jekyll and bundler

- script: |
    bundle install
  displayName: Install project dependencies

- script: |
    bundle exec jekyll build --future
  displayName: Build Site

- pwsh: |
    ./eng/scripts/Verify-Links.ps1 ./_site/index.html
  displayName: Verify site links