trigger: none
pr: none

pool:
  vmImage: 'ubuntu-latest'

steps:

- pwsh: |
    ./eng/scripts/Verify-Links.ps1 https://azure.github.io/azure-sdk/index.html
  displayName: 'azure-sdk link check'

- pwsh: |
    ./eng/scripts/Verify-Links.ps1 https://azure.github.io/azure-sdk-for-java/index.html
  displayName: 'java link check'

- pwsh: |
    ./eng/scripts/Verify-Links.ps1 https://azure.github.io/azure-sdk-for-js/index.html
  displayName: 'js link check'

- pwsh: |
    ./eng/scripts/Verify-Links.ps1 https://azure.github.io/azure-sdk-for-net/index.html
  displayName: 'net link check'

- pwsh: |
    ./eng/scripts/Verify-Links.ps1 https://azure.github.io/azure-sdk-for-python/index.html
  displayName: 'python link check'
