trigger:
- master

variables:
  BranchName: VersionUpdates
  CommitMsg: "Update package index with latest published versions"
  RepoOwner: Azure
  RepoName: azure-sdk

pool:
  vmImage: 'windows-2019'

steps:
- pwsh: |
    ./eng/scripts/Update-Release-Versions.ps1
  displayName: Update Versions locally.

- pwsh: |
    git diff --exit-code
    if ($LastExitCode -ne 0) {
      echo "##vso[task.setvariable variable=HasChanges]$true"
      echo "Changes detected so setting HasChanges=true"
    }
    else {
      echo "No changes so skipping code push"
    }
    $LastExitCode = 0

    echo "Checking out and resetting branch $(BranchName)"
    git checkout -B $(BranchName)
    $LastExitCode = 0
    echo "Commiting changes"
    git -c user.name="azure-sdk" -c user.email="azuresdk@microsoft.com" commit -am "$(CommitMsg)"
    $LastExitCode = 0
    echo "Force pushing branch $(BranchName) to https://github.com/$(RepoOwner)/$(RepoName).git"
    git push https://$(GH_TOKEN)@github.com/$(RepoOwner)/$(RepoName).git -f $(BranchName)
    $LastExitCode = 0
    echo "Reached End"
  displayName: Push any changes
  failOnStderr: false

- pwsh: |
    ./eng/scripts/Submit-PullRequest.ps1 -RepoOwner "$(RepoOwner)" -RepoName "$(RepoName)" -BaseBranch "master" -PROwner "$(RepoOwner)" -PRBranch "$(BranchName)" -AuthToken "$(GH_TOKEN)" -PRTitle "$(CommitMsg)"

  displayName: Create Pull Request
  condition: and(succeeded(), eq(variables['HasChanges'], 'true'))
