trigger:
- master

variables:
  BranchName: VersionUpdates
  CommitMsg: "[automated] Update package index with latest published versions"
  RepoOwner: Azure
  RepoName: azure-sdk

pool:
  vmImage: 'windows-2019'

steps:
- pwsh: |
    ./eng/scripts/Update-Release-Versions.ps1
  displayName: Update Versions locally.

- pwsh: |
    git diff --exit-code
    if ($LastExitCode -ne 0) {
      echo "##vso[task.setvariable variable=HasChanges]$true"
    }
    else {
      echo "No changes so skipping code push"
      exit
    }
    echo "LastExitCode = $LastExitCode"

    echo "Checking out and resetting branch $(BranchName)"
    git checkout -B $(BranchName)
    echo "LastExitCode = $LastExitCode"

    echo "Commiting changes"
    git -c user.name="azure-sdk" -c user.email="azuresdk@microsoft.com" commit -am "$(CommitMsg)"
    echo "LastExitCode = $LastExitCode"

    echo "Force pushing branch $(BranchName) to https://github.com/$(RepoOwner)/$(RepoName).git"
    git push https://$(GH_TOKEN)@github.com/$(RepoOwner)/$(RepoName).git -f $(BranchName)
    echo "LastExitCode = $LastExitCode"
  ignoreLASTEXITCODE: true
  displayName: Diff and push changes if any

- pwsh: |
    ./eng/scripts/Submit-PullRequest.ps1 -RepoOwner "$(RepoOwner)" -RepoName "$(RepoName)" -BaseBranch "master" -PROwner "$(RepoOwner)" -PRBranch "$(BranchName)" -AuthToken "$(GH_TOKEN)" -PRTitle "$(CommitMsg)"
  displayName: Create Pull Request
  condition: and(succeeded(), eq(variables['HasChanges'], 'true'))
