trigger:
- master

pool:
  vmImage: 'windows-2019'

resources:
  repositories:
    - repository: azure-sdk-tools
      type: github
      name: Azure/azure-sdk-tools
      endpoint: azure

steps:
- checkout: self
- checkout: azure-sdk-tools

- pwsh: |
    ./azure-sdk/eng/scripts/Update-Release-Versions.ps1
  displayName: Update new package from release tags

- pwsh: |
    ./azure-sdk/eng/scripts/Query-Azure-Packages.ps1
  displayName: Update packages from package manager

- template: eng/common/pipelines/templates/steps/create-pull-request.yml@azure-sdk-tools
  parameters:
    RepoName: azure-sdk
    PRBranchName: PackageVersionUpdates
    CommitMsg: "Update package index with latest published versions"
    PRTitle: "Update package index with latest published versions"
    PushArgs: -f
    WorkingDirectory: $(System.DefaultWorkingDirectory)/azure-sdk
    ScriptDirectory: $(System.DefaultWorkingDirectory)/azure-sdk-tools/eng/common/scripts
