param (
  [string]$releaseDateString = "",
  [string]$releaseTemplate = "$PSScriptRoot\release-template",
  [string]$releaseRootFolder = "$PSScriptRoot\..\..\releases",
  [bool]$publishRelease = $false,
  [string]$releaseFileName = "*",
  [string[]]$ExcludeFileNames = @()
)

# Markers that delimit the auto-generated list of archived release note pages in
# the ignore-links file. Everything between these markers is regenerated by
# Update-ArchivedReleaseNotes so it can be kept in sync automatically.
$script:ArchivedReleasesBeginMarker = "# BEGIN auto-generated archived release notes (managed by eng/scripts/Generate-Release-Structure.ps1)"
$script:ArchivedReleasesEndMarker = "# END auto-generated archived release notes"

# Parse the year/month a release note page represents from its sidebar url.
# Returns the first-of-month DateTime, or $null if the url is not a monthly release page.
function Get-ReleaseMonthFromReleaseUrl($url)
{
  if ($url -match "^/releases/(?<year>\d{4})-(?<month>\d{2})(?:-\d{2})?/index\.html$") {
    return [DateTime]::new([int]$matches["year"], [int]$matches["month"], 1)
  }
  return $null
}

# Marks monthly release notes older than $monthsToKeep as archived in the sidebar and
# regenerates the managed block of archived release note urls in the ignore-links file so
# that link verification skips (and does not recurse into) release notes older than the
# rolling window. Older notes remain reachable on the site; they are just not verified.
# Operates purely on text so it works regardless of how the yaml file was formatted.
function Update-ArchivedReleaseNotes
{
  param(
    [Parameter(Mandatory = $true)][string]$sidebarPath,
    [Parameter(Mandatory = $true)][string]$ignoreLinksPath,
    [DateTime]$referenceDate = [DateTime]::Now,
    [int]$monthsToKeep = 12,
    [string]$siteBaseUrl = "/azure-sdk"
  )

  # Anything strictly older than the first day of the month, $monthsToKeep months ago, is archived.
  $cutoff = [DateTime]::new($referenceDate.Year, $referenceDate.Month, 1).AddMonths(-$monthsToKeep)

  $lines = @(Get-Content -LiteralPath $sidebarPath)
  $newLines = new-object "System.Collections.Generic.List[string]"
  $archivedUrls = new-object "System.Collections.Generic.List[string]"

  for ($i = 0; $i -lt $lines.Count; $i++) {
    $line = $lines[$i]
    $newLines.Add($line)

    if ($line -match "^(?<indent>\s*)url:\s*[""']?(?<url>/releases/\S+?/index\.html)[""']?\s*$") {
      $indent = $matches["indent"]
      $url = $matches["url"]
      $releaseMonth = Get-ReleaseMonthFromReleaseUrl $url

      if ($releaseMonth) {
        # Consume an existing archived marker (if any) so we can recompute it.
        if (($i + 1) -lt $lines.Count -and $lines[$i + 1] -match "^\s*archived:\s*(true|false)\s*$") {
          $i++
        }

        if ($releaseMonth -lt $cutoff) {
          $newLines.Add("$($indent)archived: true")
          $archivedUrls.Add("$siteBaseUrl$url")
        }
      }
    }
  }

  Set-Content -LiteralPath $sidebarPath -Value $newLines -NoNewline:$false

  $sortedArchivedUrls = $archivedUrls | Sort-Object -Unique

  # Rebuild the ignore-links file keeping everything outside the managed block untouched.
  $ignoreLines = @(Get-Content -LiteralPath $ignoreLinksPath)
  $staticLines = new-object "System.Collections.Generic.List[string]"
  $inManagedBlock = $false
  foreach ($ignoreLine in $ignoreLines) {
    if ($ignoreLine -eq $script:ArchivedReleasesBeginMarker) { $inManagedBlock = $true; continue }
    if ($ignoreLine -eq $script:ArchivedReleasesEndMarker) { $inManagedBlock = $false; continue }
    if (!$inManagedBlock) { $staticLines.Add($ignoreLine) }
  }

  # Trim trailing blank lines from the static portion so we control the spacing.
  while ($staticLines.Count -gt 0 -and $staticLines[$staticLines.Count - 1].Trim() -eq "") {
    $staticLines.RemoveAt($staticLines.Count - 1)
  }

  $outputLines = new-object "System.Collections.Generic.List[string]"
  $outputLines.AddRange($staticLines)

  if ($sortedArchivedUrls.Count -gt 0) {
    $outputLines.Add("")
    $outputLines.Add($script:ArchivedReleasesBeginMarker)
    $outputLines.Add("# Release notes older than $monthsToKeep months. They stay available on the site but")
    $outputLines.Add("# are excluded from link verification so outdated links in old notes don't fail CI.")
    foreach ($archivedUrl in $sortedArchivedUrls) {
      $outputLines.Add($archivedUrl)
    }
    $outputLines.Add($script:ArchivedReleasesEndMarker)
  }

  Set-Content -LiteralPath $ignoreLinksPath -Value $outputLines

  Write-Host "Marked $($sortedArchivedUrls.Count) release note page(s) older than $monthsToKeep months as archived (cutoff $($cutoff.ToString('yyyy-MM')))."
}

# When dot-sourced (e.g. to reuse the functions above) stop here without running the
# folder/sidebar generation below.
if ($MyInvocation.InvocationName -eq '.') { return }

if ($releaseDateString -eq "") {
  $releaseDate = [DateTime]::Now
}
else {
  $releaseDate = [DateTime]$releaseDateString
}

$releaseString = $releaseDate.ToString("yyyy-MM")
$releaseFolder = Join-Path (Resolve-Path $releaseRootFolder) $releaseString
$releaseSidebar = Resolve-Path "$PSScriptRoot\..\..\_data\sidebars\releases_sidebar.yml"

. (Join-Path $PSScriptRoot .. common scripts Helpers PSModule-Helpers.ps1)

if ($publishRelease) {
  ### Update release sidebar
  Install-ModuleIfNotInstalled "powershell-yaml" "0.4.2" | Import-Module

  $yml = Get-Content $releaseSidebar | ConvertFrom-Yaml -Ordered

  $yearGroupName = $releaseDate.ToString("yyyy") + " Releases"
  $yearGroup = $yml.entries.folders | Where-Object { $_.title -eq $yearGroupName }

  if (!$yearGroup) {
    $yearGroup = [ordered]@{ title = "$yearGroupName"; folderitems = new-object "System.Collections.Generic.List[object]" }

    # insert in spot 1 as spot 0 is reserved for Latest
    $yml.entries[0].folders.Insert(1, $yearGroup)
  }

  $monthGroupName = $releaseDate.ToString("MMMM")
  $monthGroup = $yearGroup.folderitems | Where-Object { $_.title -eq $monthGroupName }

  if (!$monthGroup) {
    $monthGroup = [ordered]@{ title = $monthGroupName; url = "/releases/$releaseString/index.html" }
    $yearGroup.folderitems.Insert(0, $monthGroup)
  }

  $yml | ConvertTo-Yaml -OutFile $releaseSidebar -Force

  ### Archive release notes older than the rolling 12-month window so link
  ### verification only checks recent notes (older notes stay on the site).
  $ignoreLinksFile = Resolve-Path "$PSScriptRoot\ignore-links.txt"
  Update-ArchivedReleaseNotes -sidebarPath $releaseSidebar -ignoreLinksPath $ignoreLinksFile -referenceDate $releaseDate

  # If the release folder exists exit otherwise continue on and create the release folder
  if (Test-Path $releaseFolder) {
    exit 0
  }
}

if (!(Test-Path $releaseFolder)) {
  New-Item -Type Directory $releaseFolder | Out-Null
}

### Copy template files for ones that don't exist
foreach ($file in (Get-ChildItem $releaseTemplate/$releaseFileName -Exclude $ExcludeFileNames)) {
  $newFile = Join-Path $releasefolder $file.Name
  if (Test-Path $newFile) {
    Write-Host "Skipping $newFile because it already exists"
  }
  else {
    Copy-Item $file $newFile
  }
}

### Update template files with date
foreach ($file in (Get-ChildItem $releaseFolder/$releaseFileName)) {
  $fileContent = Get-Content $file -Raw

  $dateFormats = [regex]::Matches($fileContent, "%%(?<format>.*?)%%")

  foreach ($dateFormatMatch in $dateFormats)
  {
    $fileContent = $fileContent -replace $dateFormatMatch.Groups[0], $releaseDate.ToString($dateFormatMatch.Groups["format"])
  }

  $fileContent | Set-Content $file -NoNewline
}
