parameters:
- name: BaseBranchName
  type: string
  default: $(Build.SourceBranchName)
- name: PrBranchName
  type: string
  default: "CreateOrUpdateReleaseNotes"
- name: Repos
  type: object
  default:
    - azure-sdk-for-java
    - azure-sdk-for-js
    - azure-sdk-for-net
    - azure-sdk-for-python

trigger: none

pr: none

pool:
  vmImage: 'windows-2019'

resources:
  repositories:
    - repository: azure-sdk-tools
      type: github
      name: Azure/azure-sdk-tools
      endpoint: azure

steps:
  - checkout: self
  - checkout: azure-sdk-tools

  - ${{ each repo in parameters.Repos }}:
    - pwsh: |
        git clone --branch ${{ parameters.BaseBranchName }} "https://github.com/azure/${{ repo }}"
      displayName: Clone ${{ repo }} repo

    - task: PowerShell@2
      displayName: 'Generate ReleaseNotes for the Release Period'
      inputs:
        pwsh: true
        workingDirectory: $(System.DefaultWorkingDirectory)
        filePath: $(System.DefaultWorkingDirectory)/azure-sdk/eng/scripts/Generate-ReleaseNotes.ps1
        arguments: > 
          -RepositoryName ${{ repo }}
          -BaseBranchName ${{ parameters.BaseBranchName }}
          -PrBranchName ${{ parameters.PrBranchName }}
          -AuthToken $(azuresdk-github-pat)

  - template: eng/common/pipelines/templates/steps/create-pull-request.yml@azure-sdk-tools
    parameters:
      RepoName: azure-sdk
      PRBranchName: ${{ parameters.PrBranchName }}
      CommitMsg: "Create or Update Release Notes for $(thisReleasePeriod) release"
      PRTitle: "Create or Update Release Notes for $(thisReleasePeriod) release"
      PushArgs: -f
      WorkingDirectory: $(System.DefaultWorkingDirectory)/azure-sdk
      ScriptDirectory: $(System.DefaultWorkingDirectory)/azure-sdk-tools/eng/common/scripts