trigger:
- master

pool:
  name: azsdk-pool
  demands: ImageOverride -equals windows-2022

steps:

- task: PowerShell@2
  displayName: 'Generate Release Structure'
  inputs:
    pwsh: true
    filePath: ./eng/scripts/Generate-Release-Structure.ps1
    arguments: > 
      -ReleaseDateString "$(ReleaseDate)"
      -PublishRelease $$(PublishRelease)

- template: /eng/common/pipelines/templates/steps/create-pull-request.yml
  parameters:
    RepoName: azure-sdk
    PRBranchName: AddReleaseStructure
    CommitMsg: "Add new release folder structure"
    PRTitle: "Add new release folder structure"
    PushArgs: -f
