parameters:
- name: BaseBranchName
  type: string
  default: $(Build.SourceBranchName)
- name: PrBranchName
  type: string
  default: "CreateOrUpdateReleaseNotes"
- name: Repos
  type: object
  default:
    - azure-sdk-for-java
    - azure-sdk-for-js
    - azure-sdk-for-net
    - azure-sdk-for-python

trigger: none

pr: none

pool:
  vmImage: 'windows-2019'

resources:
  repositories:
    - repository: azure-sdk-tools
      type: github
      name: Azure/azure-sdk-tools
      endpoint: azure

steps:
  - checkout: self
  - checkout: azure-sdk-tools

  - pwsh: |
      $ErrorActionPreference = "Continue"
      $releasePeriod = Get-Date -Format "yyyy-MM"
      Write-Host "##vso[task.setvariable variable=ReleasePeriod]$releasePeriod"

      git checkout "origin/${{ parameters.PrBranchName }}" 2>&1 | Out-Null
      $LASTEXITCODE = 0 # This ignores any error from git checkout
      git status
    displayName: Checkout Previous PRBranch if it exist.
    workingDirectory: $(System.DefaultWorkingDirectory)/azure-sdk

  - ${{ each repo in parameters.Repos }}:
    - pwsh: |
        git clone --branch ${{ parameters.BaseBranchName }} "https://github.com/azure/${{ repo }}"
      displayName: Clone ${{ repo }} repo

    - task: PowerShell@2
      displayName: 'Generate ReleaseNotes for the Release Period'
      inputs:
        pwsh: true
        workingDirectory: $(System.DefaultWorkingDirectory)
        filePath: $(System.DefaultWorkingDirectory)/azure-sdk/eng/scripts/Generate-ReleaseNotes.ps1
        arguments: > 
          -releasePeriod $(ReleasePeriod)
          -languageRepoDirectory $(System.DefaultWorkingDirectory)/${{ repo }}
          -releaseDirectory $(System.DefaultWorkingDirectory)/azure-sdk/releases

  - template: eng/common/pipelines/templates/steps/create-pull-request.yml@azure-sdk-tools
    parameters:
      RepoName: azure-sdk
      PROwner: Azure
      PRBranchName: '${{ parameters.PrBranchName }}_$(ReleasePeriod)'
      CommitMsg: "Create or Update Release Notes for $(ReleasePeriod) release"
      PRTitle: "Create or Update Release Notes for $(ReleasePeriod) release"
      WorkingDirectory: $(System.DefaultWorkingDirectory)/azure-sdk
      ScriptDirectory: $(System.DefaultWorkingDirectory)/azure-sdk-tools/eng/common/scripts