name: Build Jekyll site for Pages

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup Pages
      uses: actions/configure-pages@v5

    - name: Build
      uses: actions/jekyll-build-pages@v1

    - name: Upload artifact
      uses: actions/upload-pages-artifact@v3

    - name: Verify CSV data contents
      shell: pwsh
      run: |
        ./eng/scripts/Update-Release-Versions.ps1 "check"

    - name: Verify site links
      shell: pwsh
      run: |
        ./eng/common/scripts/Verify-Links.ps1 -urls ./_site/index.html -ignoreLinksFile ./eng/ignore-links.txt -inputCacheFile "https://azuresdkartifacts.blob.core.windows.net/verify-links-cache/verify-links-cache.txt" -devOpsLogging:$true -baseUrl "file://$PWD/_site/"
