name: Verify Changes

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup Pages
      uses: actions/configure-pages@v5

    - name: Build
      uses: actions/jekyll-build-pages@v1

    - name: Upload artifact
      uses: actions/upload-pages-artifact@v3

    - name: Verify CSV data contents
      shell: pwsh
      run: |
        ./eng/scripts/Update-Release-Versions.ps1 "check"

    - name: Debug Info
      shell: pwsh
      run: |
        Write-Host "file://$PWD/_site/azure-sdk"
        if (Test-Path "./_site/azure-sdk/index.html") {
          Write-Host "Found ./_site/azure-sdk/index.html"
        } else {
          Write-Host "Did not find ./_site/azure-sdk/index.html"
        }
        dir ./_site

    - name: Verify site links
      shell: pwsh
      run: |
        ./eng/common/scripts/Verify-Links.ps1 -urls ./_site/azure-sdk/index.html -ignoreLinksFile ./eng/ignore-links.txt -inputCacheFile "https://azuresdkartifacts.blob.core.windows.net/verify-links-cache/verify-links-cache.txt" -devOpsLogging:$true -baseUrl "file://$PWD/_site/azure-sdk"
